import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Checkbox, Container, FormControlLabel, Grid, LinearProgress, Paper, Radio, RadioGroup, Stack, Typography } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import ArrowForwardIcon from '@mui/icons-material/ArrowForward'
import LocalShippingIcon from '@mui/icons-material/LocalShipping'
import { useNavigate } from 'react-router-dom'
import { getLocalSessionRole, useAuth } from '../contexts/AuthContext'
import { supabase } from '../lib/supabase'
import { automaticallyEvaluate, ELP_DRAFT_KEY, ElpSubmission, emptyApplicant, emptyResponses, oralQuestions, oralResponseChoices, readingPassage, readingQuestions, saveSubmission, trafficSigns, writtenChoices } from '../lib/elpAssessment'

// Versioned replacement for the retired general-English mock quiz.
const START_KEY = 'iman-cdl-start'
const steps = ['Instructions', 'A — Oral interview', 'B — Traffic signs', 'C — Reading', 'D — Written records', 'Attestation & submit']
const signDistractors = ['Continue without changing speed', 'Stop in the travel lane and abandon the vehicle', 'The sign applies only to passenger cars']

function ChoiceQuestion({ value, choices, onChange }: { value: string; choices: string[]; onChange: (value: string) => void }) {
  return <RadioGroup value={value} onChange={e => onChange(e.target.value)}>{choices.map(choice => <FormControlLabel key={choice} value={choice} control={<Radio />} label={choice} sx={{ alignItems: 'flex-start', mb: .5 }} />)}</RadioGroup>
}

export function CDLReadinessAssessment() {
  const navigate = useNavigate(); const { session, signOut } = useAuth()
  const [step,setStep]=useState(0), [applicant,setApplicant]=useState(emptyApplicant), [responses,setResponses]=useState(emptyResponses)
  const [consent,setConsent]=useState(false), [attested,setAttested]=useState(false), [error,setError]=useState('')
  useEffect(()=>{ void (async()=>{if(getLocalSessionRole()!=='student'&&(!supabase||!(await supabase.auth.getUser()).data.user)) navigate('/cdl-login/')})()
    const now=new Date();const automaticApplicant={...emptyApplicant,fullName:session?.user?.user_metadata?.full_name||session?.user?.email?.split('@')[0]||'Signed-in student',address:'Stored with student account',cityStateZip:'Florida',phone:'Stored with student account',email:session?.user?.email||'student@local.test',licenseNumber:'Not collected in assessment',licenseState:'FL',program:'Class A CDL',evaluatorName:'Automated scoring system',evaluatorTitle:'Preliminary evaluator',assessmentDate:now.toISOString().slice(0,10),assessmentTime:now.toTimeString().slice(0,5)}
    const saved=localStorage.getItem(ELP_DRAFT_KEY); if(saved) try{const d=JSON.parse(saved);setApplicant({...d.applicant,...automaticApplicant});setResponses(d.responses);setConsent(!!d.consent);setStep(d.step||0)}catch{localStorage.removeItem(ELP_DRAFT_KEY)} else setApplicant(automaticApplicant) },[navigate,session])
  useEffect(()=>localStorage.setItem(ELP_DRAFT_KEY,JSON.stringify({applicant,responses,consent,step})),[applicant,responses,consent,step])
  const setAnswer=(key:'oral'|'signs'|'reading',i:number,value:string)=>setResponses(r=>({...r,[key]:r[key].map((x,n)=>n===i?value:x)}))
  const complete=step===0?consent:step===1?responses.oral.every(Boolean):step===2?responses.signs.every(Boolean):step===3?responses.reading.every(Boolean):step===4?Object.values(responses.log).every(Boolean)&&!!responses.defects&&!!responses.licenseExpiry:attested
  const next=()=>{if(!complete)return setError('Complete every required field before continuing.');if(step===0&&!localStorage.getItem(START_KEY))localStorage.setItem(START_KEY,new Date().toISOString());setError('');setStep(s=>s+1);window.scrollTo(0,0)}
  const submit=()=>{if(!attested)return;const started=localStorage.getItem(START_KEY);const evaluation=automaticallyEvaluate(responses,applicant.evaluatorName,applicant.evaluatorTitle);const result:ElpSubmission={id:`ELP-${Date.now().toString(36).toUpperCase()}`,applicant,responses,attested,status:'EVALUATED',evaluation,submittedAt:new Date().toISOString(),duration:started?`${Math.max(1,Math.round((Date.now()-new Date(started).getTime())/60000))} minutes`:'Not recorded'};saveSubmission(result);localStorage.removeItem(ELP_DRAFT_KEY);navigate('/cdl-readiness-results/')}
  return <Box sx={{minHeight:'100vh',bgcolor:'#f5f7fb',pb:8}}><Paper square sx={{bgcolor:'#08085f',color:'white',py:2}}><Container maxWidth="lg"><Stack direction="row" justifyContent="space-between" alignItems="center"><Stack direction="row" gap={1}><LocalShippingIcon/><Typography fontWeight={900}>IMAN ELP Admission Assessment</Typography></Stack><Button sx={{color:'white'}} onClick={async()=>{await signOut();navigate('/cdl-login/')}}>Log out</Button></Stack></Container></Paper><Container maxWidth="lg" sx={{mt:4}}>
    <Typography variant="h3" fontWeight={900}>English Language Proficiency Admission Assessment</Typography><Typography color="text.secondary">School-administered screening under 49 CFR §391.11(b)(2). This is not a CDL test or certification.</Typography><LinearProgress variant="determinate" value={(step+1)/steps.length*100} sx={{my:3,height:8,borderRadius:4}}/><Typography fontWeight={800} sx={{mb:2}}>Step {step+1} of {steps.length}: {steps[step]}</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    {step===0&&<Card><CardContent sx={{p:{xs:3,md:5}}}><Alert severity="info" sx={{mb:3}}>Your account identity, date, program, and assessment record are filled automatically. There are no typed-response fields in this assessment. Allow 35–45 minutes. Questions may not be translated, simplified, or answered with coaching.</Alert><Typography fontWeight={900}>Assessment rules</Typography><Typography sx={{my:2}}>Complete every scored section independently in English. Accent alone is not a reason to fail. This school screening does not guarantee a state CDL or roadside English-proficiency determination.</Typography><FormControlLabel control={<Checkbox checked={consent} onChange={e=>setConsent(e.target.checked)}/>} label="I understand the rules and am ready to begin."/></CardContent></Card>}
    {step===1&&<Card><CardContent sx={{p:{xs:3,md:5}}}><Typography variant="h5" fontWeight={900}>Part A — Oral Interview (30 points; minimum 21)</Typography><Typography color="text.secondary" sx={{mb:3}}>The applicant answers each prompt aloud in English. The evaluator selects the matching performance level; no response needs to be typed. Question 10 must communicate all four actions.</Typography>{oralQuestions.map((q,i)=><Paper variant="outlined" sx={{p:2,mb:2}} key={q}><Typography fontWeight={900}>{i+1}. {q}</Typography><ChoiceQuestion value={responses.oral[i]} choices={oralResponseChoices} onChange={v=>setAnswer('oral',i,v)}/></Paper>)}</CardContent></Card>}
    {step===2&&<Card><CardContent sx={{p:{xs:3,md:5}}}><Typography variant="h5" fontWeight={900}>Part B — Traffic Signs (30 points; minimum 24)</Typography><Typography color="text.secondary" sx={{mb:3}}>Select the correct meaning and safe driver action. Critical signs are marked.</Typography><Grid container spacing={3}>{trafficSigns.map((s,i)=><Grid size={{xs:12,md:6}} key={s.name}><Paper variant="outlined" sx={{p:2,height:'100%'}}><Stack direction="row" gap={2} alignItems="flex-start"><Box component="img" src={s.image} alt={s.name} sx={{width:120,height:100,objectFit:'contain'}}/><Box flex={1}><Typography fontWeight={900}>{i+1}. {s.name}{s.critical?' — CRITICAL':''}</Typography><ChoiceQuestion value={responses.signs[i]} choices={[s.expected,...signDistractors]} onChange={v=>setAnswer('signs',i,v)}/></Box></Stack></Paper></Grid>)}</Grid></CardContent></Card>}
    {step===3&&<Card><CardContent sx={{p:{xs:3,md:5}}}><Typography variant="h5" fontWeight={900}>Part C — Reading (20 points; minimum 14)</Typography><Paper variant="outlined" sx={{p:3,my:3,bgcolor:'#fffbea'}}><Typography fontWeight={800}>{readingPassage}</Typography></Paper>{readingQuestions.map((q,i)=><Paper variant="outlined" sx={{p:2,mb:2}} key={q.prompt}><Typography fontWeight={900}>{i+1}. {q.prompt} ({q.max} points)</Typography><ChoiceQuestion value={responses.reading[i]} choices={q.choices} onChange={v=>setAnswer('reading',i,v)}/></Paper>)}</CardContent></Card>}
    {step===4&&<Card><CardContent sx={{p:{xs:3,md:5}}}><Typography variant="h5" fontWeight={900}>Part D — Records and Reports (20 points; minimum 14)</Typography><Typography fontWeight={800} sx={{mt:3,mb:2}}>D1. Select the correct information for each driver log field (8 points)</Typography><Grid container spacing={2}>{Object.entries({driverName:'Driver name',date:'Date',startLocation:'Start location',destination:'Destination',startTime:'Start time',onDutyTime:'Total on-duty time'}).map(([key,label])=><Grid size={{xs:12,md:6}} key={key}><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={900}>{label}</Typography><ChoiceQuestion value={responses.log[key]} choices={writtenChoices[key as keyof typeof writtenChoices]} onChange={v=>setResponses(r=>({...r,log:{...r.log,[key]:v}}))}/></Paper></Grid>)}</Grid><Typography fontWeight={800} sx={{mt:4}}>D2. Vehicle defect report (8 points)</Typography><Typography color="text.secondary">The right rear brake light does not work, and the trailer’s left rear tire has a deep cut. Select the complete, safe report.</Typography><ChoiceQuestion value={responses.defects} choices={writtenChoices.defects} onChange={v=>setResponses(r=>({...r,defects:v}))}/><Typography fontWeight={800} sx={{mt:4}}>D3. Document information (4 points)</Typography><Typography color="text.secondary">Sample license D123-456-81-001-0 expires 11/07/2030. Select its expiration date.</Typography><ChoiceQuestion value={responses.licenseExpiry} choices={writtenChoices.licenseExpiry} onChange={v=>setResponses(r=>({...r,licenseExpiry:v}))}/></CardContent></Card>}
    {step===5&&<Card><CardContent sx={{p:{xs:3,md:5}}}><Typography variant="h5" fontWeight={900}>Applicant attestation</Typography><Typography sx={{my:2}}>I completed this assessment independently; my information and responses are accurate; a passing school result does not guarantee a state CDL or roadside ELP determination; and I may be assigned remediation and a retest.</Typography><FormControlLabel control={<Checkbox checked={attested} onChange={e=>setAttested(e.target.checked)}/>} label="I agree and sign electronically."/><Alert severity="info" sx={{mt:3}}>Your selections will be scored immediately. PASS requires at least 80/100, every section minimum, and all four critical signs. An authorized evaluator may review the result.</Alert></CardContent></Card>}
    <Stack direction="row" justifyContent="space-between" sx={{mt:3}}><Button disabled={!step} startIcon={<ArrowBackIcon/>} onClick={()=>{setError('');setStep(s=>s-1);window.scrollTo(0,0)}}>Previous</Button>{step<5?<Button variant="contained" endIcon={<ArrowForwardIcon/>} onClick={next}>Continue</Button>:<Button variant="contained" color="secondary" disabled={!attested} onClick={submit}>Submit and view score</Button>}</Stack>
  </Container></Box>
}
