import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, Container, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import DownloadIcon from '@mui/icons-material/Download'; import EmailIcon from '@mui/icons-material/Email'; import LogoutIcon from '@mui/icons-material/Logout'; import LocalShippingIcon from '@mui/icons-material/LocalShipping'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { ELP_DRAFT_KEY, ELP_RESULT_KEY, ELP_SUBMISSIONS_KEY, ElpSubmission } from '../lib/elpAssessment'

export function CDLReadinessResults(){
 const navigate=useNavigate(), {signOut}=useAuth(); const [result,setResult]=useState<ElpSubmission|null>(null),[email,setEmail]=useState(''),[notice,setNotice]=useState(''),[emailError,setEmailError]=useState(''),[emailing,setEmailing]=useState(false)
 useEffect(()=>{const refresh=()=>{const raw=localStorage.getItem(ELP_RESULT_KEY);if(!raw)return navigate('/cdl-readiness/');const current:ElpSubmission=JSON.parse(raw);const list:ElpSubmission[]=JSON.parse(localStorage.getItem(ELP_SUBMISSIONS_KEY)||'[]');const latest=list.find(x=>x.id===current.id)||current;setResult(latest);setEmail(latest.applicant?.email||'')};refresh();window.addEventListener('storage',refresh);return()=>window.removeEventListener('storage',refresh)},[navigate])
 if(!result)return null; const ev=result.evaluation
 const csv=()=>{const q=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const rows:any[][]=[['Assessment ID',result.id],['Applicant',result.applicant.fullName],['Email',result.applicant.email],['Submitted',new Date(result.submittedAt).toLocaleString()],['Duration',result.duration],['Status',ev?ev.decision:'PENDING EVALUATOR REVIEW']];if(ev){rows.push(['Total',`${ev.score}/100`],['Prohibited assistance',ev.prohibitedAssistance?'Yes':'No'],[],['Section','Score','Maximum','Minimum','Passed'],...ev.sections.map(s=>[s.section,s.score,s.max,s.minimum,s.passed?'Yes':'No']))}rows.push([],['Applicant responses']);result.responses.oral.forEach((a,i)=>rows.push([`Oral ${i+1}`,a]));result.responses.signs.forEach((a,i)=>rows.push([`Sign ${i+1}`,a]));result.responses.reading.forEach((a,i)=>rows.push([`Reading ${i+1}`,a]));rows.push(['Defect report',result.responses.defects],['License expiration',result.responses.licenseExpiry]);return rows.map(r=>r.map(q).join(',')).join('\n')}
 const download=()=>{const url=URL.createObjectURL(new Blob([csv()],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`iman-elp-${result.id}.csv`;a.click();URL.revokeObjectURL(url)}
 const send=async()=>{setNotice('');setEmailError('');if(!email.trim())return setEmailError('Enter an email address.');setEmailing(true);try{const response=await fetch('/api/send-assessment-report.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipient:email.trim(),result})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'The report could not be emailed.');setNotice(`Report emailed to ${email}.`)}catch(e){setEmailError(e instanceof Error?e.message:'The report could not be emailed.')}finally{setEmailing(false)}}
 const logout=async()=>{await signOut();navigate('/cdl-login/',{replace:true})}
 return <Box sx={{minHeight:'100vh',bgcolor:'#f5f7fb',py:7}}><Container maxWidth="lg"><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{mb:4}}><Stack direction="row" gap={2} alignItems="center"><LocalShippingIcon sx={{fontSize:46,color:'#d61f2c'}}/><Box><Typography variant="h3" fontWeight={900}>ELP Admission Assessment</Typography><Typography>Assessment record</Typography></Box></Stack><Button variant="outlined" startIcon={<LogoutIcon/>} onClick={logout}>Log out</Button></Stack>
 <Alert severity={ev?(ev.decision==='PASS'?'success':'warning'):'info'} sx={{mb:3}}><Typography variant="h5" fontWeight={900}>{ev?ev.decision:'Pending evaluator review'}</Typography><Typography>{ev?`Final score: ${ev.score}/100. ${ev.notes||''}`:'Your responses were submitted. A trained evaluator must score each item and critical requirement before a final decision is available.'}</Typography></Alert>
 <Paper sx={{p:4,borderRadius:3,mb:3}}><Typography fontWeight={900}>Assessment ID: {result.id}</Typography><Typography>Applicant: {result.applicant.fullName}</Typography><Typography>Submitted: {new Date(result.submittedAt).toLocaleString()} · {result.duration}</Typography></Paper>
 {ev&&<Card sx={{mb:3}}><CardContent><Typography variant="h5" fontWeight={900} sx={{mb:2}}>Scoring decision</Typography><Table><TableHead><TableRow><TableCell>Section</TableCell><TableCell>Score</TableCell><TableCell>Minimum</TableCell><TableCell>Result</TableCell></TableRow></TableHead><TableBody>{ev.sections.map(s=><TableRow key={s.section}><TableCell>{s.section}</TableCell><TableCell>{s.score}/{s.max}</TableCell><TableCell>{s.minimum}</TableCell><TableCell><Chip size="small" color={s.passed?'success':'error'} label={s.passed?'Passed':'Minimum missed'}/></TableCell></TableRow>)}</TableBody></Table><Typography sx={{mt:2}}>Critical signs: {ev.criticalPassed.every(Boolean)?'All passed':'One or more missed'} · Prohibited assistance: {ev.prohibitedAssistance?'Yes':'No'}</Typography></CardContent></Card>}
 <Paper sx={{p:4,borderRadius:3}}><Typography variant="h5" fontWeight={900}>Download or email this record</Typography><Typography color="text.secondary" sx={{mb:2}}>The report states whether the submission is pending or contains a completed evaluator decision.</Typography>{notice&&<Alert severity="success" sx={{mb:2}}>{notice}</Alert>}{emailError&&<Alert severity="error" sx={{mb:2}}>{emailError}</Alert>}<Stack direction={{xs:'column',md:'row'}} gap={2}><Button variant="contained" startIcon={<DownloadIcon/>} onClick={download}>Download report</Button><TextField fullWidth label="Email address" value={email} onChange={e=>setEmail(e.target.value)}/><Button variant="outlined" startIcon={<EmailIcon/>} disabled={emailing} onClick={send}>{emailing?'Sending…':'Email report'}</Button></Stack></Paper>
 <Button sx={{mt:3}} onClick={()=>{localStorage.removeItem(ELP_RESULT_KEY);localStorage.removeItem(ELP_DRAFT_KEY);navigate('/cdl-readiness/')}}>Start a new assessment</Button></Container></Box>
}
