import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Checkbox, Container, FormControlLabel, Grid, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { Link } from 'react-router-dom'
import { calculateEvaluation, ELP_RESULT_KEY, ELP_SUBMISSIONS_KEY, ElpSubmission, loadSubmissions, oralQuestions, readingQuestions, saveSubmission, trafficSigns } from '../../lib/elpAssessment'

const oralRubric='3 = clear, relevant, understandable and sufficiently detailed; 2 = generally understandable with minor errors/repetition; 1 = fragmented/incomplete with substantial difficulty; 0 = no understandable/relevant response or prohibited assistance.'
const signRubric='3 = correct meaning and action; 2 = correct meaning but incomplete action; 1 = partial recognition; 0 = incorrect or no response.'
const bounded=(value:string,max:number)=>Math.max(0,Math.min(max,Number(value)||0))

export function CDLInstructorDashboard(){
 const [items,setItems]=useState<ElpSubmission[]>([]),[selected,setSelected]=useState<ElpSubmission|null>(null),[notice,setNotice]=useState('')
 const [oral,setOral]=useState<number[]>(Array(10).fill(0)),[signs,setSigns]=useState<number[]>(Array(10).fill(0)),[reading,setReading]=useState<number[]>(Array(8).fill(0)),[critical,setCritical]=useState<boolean[]>(Array(4).fill(false))
 const [logScore,setLogScore]=useState(0),[defectScore,setDefectScore]=useState(0),[licenseScore,setLicenseScore]=useState(0),[assistance,setAssistance]=useState(false),[evaluator,setEvaluator]=useState(''),[title,setTitle]=useState(''),[notes,setNotes]=useState('')
 const load=()=>{void loadSubmissions().then(setItems)};useEffect(load,[])
 const choose=(s:ElpSubmission)=>{setSelected(s);const e=s.evaluation;setOral(e?.oralScores||Array(10).fill(0));setSigns(e?.signScores||Array(10).fill(0));setReading(e?.readingScores||Array(8).fill(0));setCritical(e?.criticalPassed||Array(4).fill(false));setLogScore(e?.logScore||0);setDefectScore(e?.defectScore||0);setLicenseScore(e?.licenseScore||0);setAssistance(e?.prohibitedAssistance||false);setEvaluator(e?.evaluatorName||s.applicant.evaluatorName);setTitle(e?.evaluatorTitle||s.applicant.evaluatorTitle);setNotes(e?.notes||'');setNotice('');window.scrollTo(0,0)}
 const save=()=>{if(!selected||!evaluator||!title)return setNotice('Evaluator name and title are required.');const evaluation=calculateEvaluation({oralScores:oral,signScores:signs,readingScores:reading,logScore,defectScore,licenseScore,criticalPassed:critical,prohibitedAssistance:assistance,evaluatorName:evaluator,evaluatorTitle:title,notes});const updated={...selected,status:'EVALUATED' as const,evaluation};const list=items.map(x=>x.id===updated.id?updated:x);setItems(list);setSelected(updated);localStorage.setItem(ELP_SUBMISSIONS_KEY,JSON.stringify(list));const current=localStorage.getItem(ELP_RESULT_KEY);if(current&&JSON.parse(current).id===updated.id)localStorage.setItem(ELP_RESULT_KEY,JSON.stringify(updated));void saveSubmission(updated).then(()=>setNotice(`Saved final decision: ${evaluation.decision} (${evaluation.score}/100).`)).catch(e=>setNotice(e instanceof Error?e.message:'Could not save the evaluation.'))}
 const scoreField=(label:string,value:number,max:number,onChange:(n:number)=>void)=><TextField select size="small" label={label} value={value} onChange={e=>onChange(bounded(e.target.value,max))}>{Array.from({length:max+1},(_,i)=><MenuItem key={i} value={i}>{i}</MenuItem>)}</TextField>
 if(selected)return <Box sx={{bgcolor:'#f5f7fb',minHeight:'100vh',py:5}}><Container maxWidth="lg"><Button onClick={()=>setSelected(null)}>← All submissions</Button><Typography variant="h3" fontWeight={900} sx={{my:2}}>Evaluate {selected.applicant.fullName}</Typography><Alert severity="info" sx={{mb:3}}>Apply the attached packet consistently. Accent alone is not a failure. Do not simplify, translate, define, lead, coach, or help during scored sections.</Alert>{notice&&<Alert severity={notice.startsWith('Saved')?'success':'error'} sx={{mb:2}}>{notice}</Alert>}
 <Card sx={{mb:3}}><CardContent><Typography variant="h5" fontWeight={900}>A — Oral Interview</Typography><Typography color="text.secondary" sx={{mb:2}}>{oralRubric}</Typography>{oralQuestions.map((q,i)=><Paper variant="outlined" sx={{p:2,mb:1}} key={q}><Typography fontWeight={800}>{i+1}. {q}</Typography><Typography sx={{my:1}}>{selected.responses.oral[i]}</Typography>{scoreField('Score 0–3',oral[i],3,n=>setOral(a=>a.map((v,x)=>x===i?n:v)))}</Paper>)}</CardContent></Card>
 <Card sx={{mb:3}}><CardContent><Typography variant="h5" fontWeight={900}>B — Traffic Signs</Typography><Typography color="text.secondary" sx={{mb:2}}>{signRubric}</Typography>{trafficSigns.map((s,i)=><Paper variant="outlined" sx={{p:2,mb:1}} key={s.name}><Stack direction={{xs:'column',md:'row'}} gap={2} alignItems={{md:'center'}}><Box component="img" src={s.image} alt={s.name} sx={{width:90,height:70,objectFit:'contain'}}/><Box flex={1}><Typography fontWeight={800}>{s.name}{s.critical?' — CRITICAL':''}</Typography><Typography>Response: {selected.responses.signs[i]}</Typography><Typography variant="body2" color="text.secondary">Expected: {s.expected}</Typography></Box>{scoreField('Score 0–3',signs[i],3,n=>setSigns(a=>a.map((v,x)=>x===i?n:v)))}</Stack></Paper>)}<Typography fontWeight={900} sx={{mt:2}}>Critical requirements</Typography>{trafficSigns.filter(s=>s.critical).map((s,i)=><FormControlLabel key={s.name} control={<Checkbox checked={critical[i]} onChange={e=>setCritical(a=>a.map((v,x)=>x===i?e.target.checked:v))}/>} label={`${s.name} was answered correctly`}/>)}</CardContent></Card>
 <Card sx={{mb:3}}><CardContent><Typography variant="h5" fontWeight={900}>C — Reading</Typography>{readingQuestions.map((q,i)=><Paper variant="outlined" sx={{p:2,mb:1}} key={q.prompt}><Typography fontWeight={800}>{q.prompt}</Typography><Typography sx={{my:1}}>{selected.responses.reading[i]}</Typography>{scoreField(`Score 0–${q.max}`,reading[i],q.max,n=>setReading(a=>a.map((v,x)=>x===i?n:v)))}</Paper>)}</CardContent></Card>
 <Card sx={{mb:3}}><CardContent><Typography variant="h5" fontWeight={900}>D — Written Records</Typography><Typography fontWeight={800} sx={{mt:2}}>D1 Log entry</Typography><Typography>{Object.entries(selected.responses.log).map(([k,v])=>`${k}: ${v}`).join(' · ')}</Typography><Box sx={{my:2}}>{scoreField('D1 score 0–8',logScore,8,setLogScore)}</Box><Typography fontWeight={800}>D2 Defect report</Typography><Typography>{selected.responses.defects}</Typography><Box sx={{my:2}}>{scoreField('D2 score 0–8',defectScore,8,setDefectScore)}</Box><Typography fontWeight={800}>D3 License expiration</Typography><Typography>{selected.responses.licenseExpiry}</Typography><Box sx={{mt:2}}>{scoreField('D3 score 0–4',licenseScore,4,setLicenseScore)}</Box></CardContent></Card>
 <Paper sx={{p:4}}><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Evaluator name" value={evaluator} onChange={e=>setEvaluator(e.target.value)}/></Grid><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Evaluator title" value={title} onChange={e=>setTitle(e.target.value)}/></Grid><Grid size={{xs:12}}><FormControlLabel control={<Checkbox checked={assistance} onChange={e=>setAssistance(e.target.checked)}/>} label="Prohibited assistance was used (forces NOT YET QUALIFIED)"/><TextField fullWidth multiline minRows={3} label="Remediation / evaluator notes" value={notes} onChange={e=>setNotes(e.target.value)}/></Grid></Grid><Alert severity="warning" sx={{my:2}}>PASS requires 80/100, A ≥21, B ≥24, C ≥14, D ≥14, all four critical signs correct, and no prohibited assistance.</Alert><Button variant="contained" color="secondary" onClick={save}>Save evaluator decision</Button></Paper></Container></Box>
 return <Box sx={{minHeight:'100vh',bgcolor:'#f5f7fb',py:6}}><Container maxWidth="xl"><Button component={Link} to="/admin/">← Dashboard</Button><Typography variant="h3" fontWeight={900} sx={{my:2}}>ELP Assessment Submissions</Typography><Typography color="text.secondary" sx={{mb:3}}>Evaluator review is required before a final decision.</Typography><Paper sx={{p:3}}><Table><TableHead><TableRow><TableCell>Applicant</TableCell><TableCell>Submitted</TableCell><TableCell>Status</TableCell><TableCell>Decision</TableCell><TableCell>Action</TableCell></TableRow></TableHead><TableBody>{items.length?items.map(s=><TableRow key={s.id}><TableCell><Typography fontWeight={800}>{s.applicant.fullName}</Typography><Typography variant="body2">{s.applicant.email}</Typography></TableCell><TableCell>{new Date(s.submittedAt).toLocaleString()}</TableCell><TableCell>{s.status}</TableCell><TableCell>{s.evaluation?`${s.evaluation.decision} (${s.evaluation.score}/100)`:'Pending'}</TableCell><TableCell><Button onClick={()=>choose(s)}>{s.evaluation?'Review / edit':'Evaluate'}</Button></TableCell></TableRow>):<TableRow><TableCell colSpan={5}>No local submissions yet.</TableCell></TableRow>}</TableBody></Table></Paper><Alert severity="info" sx={{mt:3}}>Retest only after documented remediation; wait a recommended 7 days, use different signs/order and a fresh scenario, and allow no more than two attempts within 90 days unless the director approves.</Alert></Container></Box>
}
